/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FlayerRouteImport } from './routes/flayer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArsipRouteImport } from './routes/arsip'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuratIndexRouteImport } from './routes/surat/index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'

// Modul Rapat & Kalender Flat Routes
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as RapatIndexRouteImport } from './routes/rapat.index'
import { Route as RapatBaruRouteImport } from './routes/rapat.baru'
import { Route as RapatPengajuanRouteImport } from './routes/rapat.pengajuan'
import { Route as RapatIdRouteImport } from './routes/rapat.$id'
import { Route as UndanganIndexRouteImport } from './routes/undangan.index'
import { Route as UndanganIdRouteImport } from './routes/undangan.$id'
import { Route as ScanQrRouteImport } from './routes/scan-qr'
import { Route as PengurusIndexRouteImport } from './routes/pengurus.index'
import { Route as LaporanRapatRouteImport } from './routes/laporan-rapat'
import { Route as TugasRouteImport } from './routes/tugas'
import { Route as RiwayatKehadiranRouteImport } from './routes/riwayat-kehadiran'

const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlayerRoute = FlayerRouteImport.update({
  id: '/flayer',
  path: '/flayer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipRoute = ArsipRouteImport.update({
  id: '/arsip',
  path: '/arsip',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuratIndexRoute = SuratIndexRouteImport.update({
  id: '/surat/',
  path: '/surat/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)

// Modul Rapat Updates
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const RapatIndexRoute = RapatIndexRouteImport.update({
  id: '/rapat/',
  path: '/rapat/',
  getParentRoute: () => rootRouteImport,
} as any)
const RapatBaruRoute = RapatBaruRouteImport.update({
  id: '/rapat/baru',
  path: '/rapat/baru',
  getParentRoute: () => rootRouteImport,
} as any)
const RapatPengajuanRoute = RapatPengajuanRouteImport.update({
  id: '/rapat/pengajuan',
  path: '/rapat/pengajuan',
  getParentRoute: () => rootRouteImport,
} as any)
const RapatIdRoute = RapatIdRouteImport.update({
  id: '/rapat/$id',
  path: '/rapat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UndanganIndexRoute = UndanganIndexRouteImport.update({
  id: '/undangan/',
  path: '/undangan/',
  getParentRoute: () => rootRouteImport,
} as any)
const UndanganIdRoute = UndanganIdRouteImport.update({
  id: '/undangan/$id',
  path: '/undangan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanQrRoute = ScanQrRouteImport.update({
  id: '/scan-qr',
  path: '/scan-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PengurusIndexRoute = PengurusIndexRouteImport.update({
  id: '/pengurus/',
  path: '/pengurus/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRapatRoute = LaporanRapatRouteImport.update({
  id: '/laporan-rapat',
  path: '/laporan-rapat',
  getParentRoute: () => rootRouteImport,
} as any)
const TugasRoute = TugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatKehadiranRoute = RiwayatKehadiranRouteImport.update({
  id: '/riwayat-kehadiran',
  path: '/riwayat-kehadiran',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arsip': typeof ArsipRoute
  '/dashboard': typeof DashboardRoute
  '/flayer': typeof FlayerRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/verify/$id': typeof VerifyIdRoute
  '/surat/': typeof SuratIndexRoute
  '/kalender': typeof KalenderRoute
  '/rapat/': typeof RapatIndexRoute
  '/rapat/baru': typeof RapatBaruRoute
  '/rapat/pengajuan': typeof RapatPengajuanRoute
  '/rapat/$id': typeof RapatIdRoute
  '/undangan/': typeof UndanganIndexRoute
  '/undangan/$id': typeof UndanganIdRoute
  '/scan-qr': typeof ScanQrRoute
  '/pengurus/': typeof PengurusIndexRoute
  '/laporan-rapat': typeof LaporanRapatRoute
  '/tugas': typeof TugasRoute
  '/riwayat-kehadiran': typeof RiwayatKehadiranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arsip': typeof ArsipRoute
  '/dashboard': typeof DashboardRoute
  '/flayer': typeof FlayerRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/verify/$id': typeof VerifyIdRoute
  '/surat': typeof SuratIndexRoute
  '/kalender': typeof KalenderRoute
  '/rapat': typeof RapatIndexRoute
  '/rapat/baru': typeof RapatBaruRoute
  '/rapat/pengajuan': typeof RapatPengajuanRoute
  '/rapat/$id': typeof RapatIdRoute
  '/undangan': typeof UndanganIndexRoute
  '/undangan/$id': typeof UndanganIdRoute
  '/scan-qr': typeof ScanQrRoute
  '/pengurus': typeof PengurusIndexRoute
  '/laporan-rapat': typeof LaporanRapatRoute
  '/tugas': typeof TugasRoute
  '/riwayat-kehadiran': typeof RiwayatKehadiranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arsip': typeof ArsipRoute
  '/dashboard': typeof DashboardRoute
  '/flayer': typeof FlayerRoute
  '/login': typeof LoginRoute
  '/pengaturan': typeof PengaturanRoute
  '/verify/$id': typeof VerifyIdRoute
  '/surat/': typeof SuratIndexRoute
  '/kalender': typeof KalenderRoute
  '/rapat/': typeof RapatIndexRoute
  '/rapat/baru': typeof RapatBaruRoute
  '/rapat/pengajuan': typeof RapatPengajuanRoute
  '/rapat/$id': typeof RapatIdRoute
  '/undangan/': typeof UndanganIndexRoute
  '/undangan/$id': typeof UndanganIdRoute
  '/scan-qr': typeof ScanQrRoute
  '/pengurus/': typeof PengurusIndexRoute
  '/laporan-rapat': typeof LaporanRapatRoute
  '/tugas': typeof TugasRoute
  '/riwayat-kehadiran': typeof RiwayatKehadiranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arsip'
    | '/dashboard'
    | '/flayer'
    | '/login'
    | '/pengaturan'
    | '/verify/$id'
    | '/surat/'
    | '/kalender'
    | '/rapat/'
    | '/rapat/baru'
    | '/rapat/pengajuan'
    | '/rapat/$id'
    | '/undangan/'
    | '/undangan/$id'
    | '/scan-qr'
    | '/pengurus/'
    | '/laporan-rapat'
    | '/tugas'
    | '/riwayat-kehadiran'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arsip'
    | '/dashboard'
    | '/flayer'
    | '/login'
    | '/pengaturan'
    | '/verify/$id'
    | '/surat'
    | '/kalender'
    | '/rapat'
    | '/rapat/baru'
    | '/rapat/pengajuan'
    | '/rapat/$id'
    | '/undangan'
    | '/undangan/$id'
    | '/scan-qr'
    | '/pengurus'
    | '/laporan-rapat'
    | '/tugas'
    | '/riwayat-kehadiran'
  id:
    | '__root__'
    | '/'
    | '/arsip'
    | '/dashboard'
    | '/flayer'
    | '/login'
    | '/pengaturan'
    | '/verify/$id'
    | '/surat/'
    | '/kalender'
    | '/rapat/'
    | '/rapat/baru'
    | '/rapat/pengajuan'
    | '/rapat/$id'
    | '/undangan/'
    | '/undangan/$id'
    | '/scan-qr'
    | '/pengurus/'
    | '/laporan-rapat'
    | '/tugas'
    | '/riwayat-kehadiran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArsipRoute: typeof ArsipRoute
  DashboardRoute: typeof DashboardRoute
  FlayerRoute: typeof FlayerRoute
  LoginRoute: typeof LoginRoute
  PengaturanRoute: typeof PengaturanRoute
  VerifyIdRoute: typeof VerifyIdRoute
  SuratIndexRoute: typeof SuratIndexRoute
  KalenderRoute: typeof KalenderRoute
  RapatIndexRoute: typeof RapatIndexRoute
  RapatBaruRoute: typeof RapatBaruRoute
  RapatPengajuanRoute: typeof RapatPengajuanRoute
  RapatIdRoute: typeof RapatIdRoute
  UndanganIndexRoute: typeof UndanganIndexRoute
  UndanganIdRoute: typeof UndanganIdRoute
  ScanQrRoute: typeof ScanQrRoute
  PengurusIndexRoute: typeof PengurusIndexRoute
  LaporanRapatRoute: typeof LaporanRapatRoute
  TugasRoute: typeof TugasRoute
  RiwayatKehadiranRoute: typeof RiwayatKehadiranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flayer': {
      id: '/flayer'
      path: '/flayer'
      fullPath: '/flayer'
      preLoaderRoute: typeof FlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip': {
      id: '/arsip'
      path: '/arsip'
      fullPath: '/arsip'
      preLoaderRoute: typeof ArsipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surat/': {
      id: '/surat/'
      path: '/surat'
      fullPath: '/surat/'
      preLoaderRoute: typeof SuratIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapat/': {
      id: '/rapat/'
      path: '/rapat'
      fullPath: '/rapat/'
      preLoaderRoute: typeof RapatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapat/baru': {
      id: '/rapat/baru'
      path: '/rapat/baru'
      fullPath: '/rapat/baru'
      preLoaderRoute: typeof RapatBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapat/pengajuan': {
      id: '/rapat/pengajuan'
      path: '/rapat/pengajuan'
      fullPath: '/rapat/pengajuan'
      preLoaderRoute: typeof RapatPengajuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapat/$id': {
      id: '/rapat/$id'
      path: '/rapat/$id'
      fullPath: '/rapat/$id'
      preLoaderRoute: typeof RapatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undangan/': {
      id: '/undangan/'
      path: '/undangan'
      fullPath: '/undangan/'
      preLoaderRoute: typeof UndanganIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undangan/$id': {
      id: '/undangan/$id'
      path: '/undangan/$id'
      fullPath: '/undangan/$id'
      preLoaderRoute: typeof UndanganIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-qr': {
      id: '/scan-qr'
      path: '/scan-qr'
      fullPath: '/scan-qr'
      preLoaderRoute: typeof ScanQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengurus/': {
      id: '/pengurus/'
      path: '/pengurus'
      fullPath: '/pengurus/'
      preLoaderRoute: typeof PengurusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan-rapat': {
      id: '/laporan-rapat'
      path: '/laporan-rapat'
      fullPath: '/laporan-rapat'
      preLoaderRoute: typeof LaporanRapatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tugas': {
      id: '/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof TugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat-kehadiran': {
      id: '/riwayat-kehadiran'
      path: '/riwayat-kehadiran'
      fullPath: '/riwayat-kehadiran'
      preLoaderRoute: typeof RiwayatKehadiranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArsipRoute: ArsipRoute,
  DashboardRoute: DashboardRoute,
  FlayerRoute: FlayerRoute,
  LoginRoute: LoginRoute,
  PengaturanRoute: PengaturanRoute,
  VerifyIdRoute: VerifyIdRoute,
  SuratIndexRoute: SuratIndexRoute,
  KalenderRoute: KalenderRoute,
  RapatIndexRoute: RapatIndexRoute,
  RapatBaruRoute: RapatBaruRoute,
  RapatPengajuanRoute: RapatPengajuanRoute,
  RapatIdRoute: RapatIdRoute,
  UndanganIndexRoute: UndanganIndexRoute,
  UndanganIdRoute: UndanganIdRoute,
  ScanQrRoute: ScanQrRoute,
  PengurusIndexRoute: PengurusIndexRoute,
  LaporanRapatRoute: LaporanRapatRoute,
  TugasRoute: TugasRoute,
  RiwayatKehadiranRoute: RiwayatKehadiranRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
